### PR TITLE
Fix remote URL template loading

### PR DESCRIPTION
**Pull request by cap10morgan**
While it's not the most performant approach (yet), we would like to try loading templates from remote URLs. Handlebars.java needs a little help to support this, hence the proxy of URLTemplateLoader.

Is this something you'd be willing to support in hbs?

### CODE REVIEW

**Comment by sunng87** [comment]
I didn't see needs for loading remote template source, but if it's useful to you I'm 100% OK to add support for this. Would you mind adding a test case for this feature?

**Comment by cap10morgan** [comment]
@sunng87 Test case added. Thanks!

**Comment by sunng87** [comment]
@cap10morgan Thanks! Maybe you forgot to add `hbs.test-web-server` into the commit ?

**Comment by cap10morgan** [comment]
Yep, sorry about that. Pushed now.

I also pushed a small project.clj change that should have been in my last PR. It removes the java compilation options that are no longer being used. Didn't seem worth its own PR, but I'd be happy to split it out if you prefer.

**Comment by sunng87** [comment]
Thanks for the great patch! It's OK to put it in the PR. I have merged the patch and will create a new release soon.

**Pull request merged**
